sudo: required
language: node_js
node_js:
  - 6
services:
  - docker
jobs:
  include:
    - stage: cd
      git:
        depth: 999999
      env: 'Type=Continuous Deployment'
      script:
        - docker run -dit --name copr -v $(pwd):/builddir imlteam/dotnet-docker /usr/sbin/init
        - docker exec -it copr bash -c 'yum install -y rpmdevtools copr-cli git'
        - docker exec -it copr bash -c "cd /builddir && fake run build.fsx --release=\$(git rev-list HEAD | wc -l) --copr-login=$COPR_LOGIN --copr-username=$COPR_USERNAME --copr-token=$COPR_TOKEN"
    - stage: deploy-npm
      env: Type='npm Deploy'
      script: skip
      before_deploy:
        - npm i --ci
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
    - stage: deploy-copr
      env: Type='Copr deploy'
      language: generic
      script:
        - docker run -dit --name copr -v $(pwd):/builddir imlteam/dotnet-docker /usr/sbin/init
        - docker exec -it copr bash -c 'yum install -y rpmdevtools copr-cli'
        - docker exec -it copr bash -c 'cd /builddir && fake run build.fsx --copr-login=$COPR_LOGIN --copr-username=$COPR_USERNAME --copr-token=$COPR_TOKEN --prod'
stages:
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
  - name: deploy-copr
    if: branch =~ ^v\d+\.\d+\.\d+-.+$